language: java

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

# https://joerglenhard.wordpress.com/2013/10/01/using-travis-ci-with-gradle-wrapper
before_install:
 - chmod +x gradlew

env:
- TERM=dumb

after_success:
- ./gradlew jacocoTestReport coveralls